-- =============================================================================
-- Quais migrations já estão no banco? (gerado a partir de supabase/migrations/)
-- Só leitura. Verifica se os objetos que cada arquivo cria existem no catálogo.
--
-- APLICADA  = todos os objetos verificados existem
-- PARCIAL   = alguns existem e outros não  <- olhar com atenção, já aconteceu
--             de um GRANT/coluna entrar pela metade neste repo
-- FALTANDO  = nenhum objeto existe
--
-- 20 migrations não criam objeto (só UPDATE/backfill/GRANT) e não
-- aparecem aqui — não dá para detectá-las pelo catálogo.
-- =============================================================================
with alvo(arquivo, tipo, obj, extra) as (values
  ('20260129_create_imoveis_corretores.sql','table','imoveis_corretores',null),
  ('20260129_create_imoveis_corretores.sql','index','idx_imoveis_corretores_tenant',null),
  ('20260129_create_imoveis_corretores.sql','index','idx_imoveis_corretores_codigo',null),
  ('20260203_add_corretor_id_to_imoveis_corretores.sql','index','idx_imoveis_corretores_corretor_id',null),
  ('20260203_add_corretor_id_to_imoveis_corretores.sql','column','imoveis_corretores','corretor_id'),
  ('20260204_add_lead_type_to_leads.sql','index','idx_leads_tenant_lead_type',null),
  ('20260204_add_lead_type_to_leads.sql','index','idx_leads_tenant_agent_lead_type',null),
  ('20260204_add_lead_type_to_leads.sql','index','idx_leads_tenant_status_lead_type',null),
  ('20260205_add_attended_by_id_to_kenlo_leads.sql','index','idx_kenlo_leads_attended_by_id',null),
  ('20260205_add_attended_by_id_to_kenlo_leads.sql','index','idx_kenlo_leads_tenant_attended',null),
  ('20260205_add_attended_by_id_to_kenlo_leads.sql','column','kenlo_leads','attended_by_id'),
  ('20260205_create_roleta_participantes.sql','table','roleta_participantes',null),
  ('20260205_create_roleta_participantes.sql','function','update_roleta_participantes_updated_at',null),
  ('20260205_create_roleta_participantes.sql','index','idx_roleta_participantes_tenant',null),
  ('20260205_create_tenant_source_images.sql','table','tenant_source_images',null),
  ('20260205_create_tenant_source_images.sql','index','idx_tenant_source_images_tenant',null),
  ('20260205_create_tenant_source_images.sql','policy','tenant_source_images','Users can view own tenant source images'),
  ('20260210_create_google_calendar_tokens.sql','table','google_calendar_tokens',null),
  ('20260210_create_google_calendar_tokens.sql','index','idx_google_calendar_tokens_user_id',null),
  ('20260210_create_google_calendar_tokens.sql','index','idx_google_calendar_tokens_tenant_id',null),
  ('20260214_create_estudos_mercado.sql','table','estudos_mercado',null),
  ('20260214_create_estudos_mercado.sql','table','estudos_mercado_amostras',null),
  ('20260214_create_estudos_mercado.sql','index','idx_estudos_mercado_tenant',null),
  ('20260214_create_tenant_api_keys.sql','table','tenant_api_keys',null),
  ('20260214_create_tenant_api_keys.sql','index','idx_tenant_api_keys_tenant_provider',null),
  ('20260214_create_tenant_api_keys.sql','policy','tenant_api_keys','tenant_api_keys_select'),
  ('20260220_add_allowed_features_to_tenants.sql','index','idx_tenants_allowed_features',null),
  ('20260220_add_allowed_features_to_tenants.sql','column','tenants','allowed_features'),
  ('20260220_add_tenants_update_policy.sql','policy','tenants','Owner can select all tenants'),
  ('20260220_add_tenants_update_policy.sql','policy','tenants','Owner can update tenants'),
  ('20260220_add_tenants_update_policy.sql','policy','tenants','Owner can insert tenants'),
  ('20260220_fix_tenants_rls_policy.sql','policy','tenants','tenants_select_policy'),
  ('20260220_fix_tenants_rls_policy.sql','policy','tenants','tenants_insert_policy'),
  ('20260220_fix_tenants_rls_policy.sql','policy','tenants','tenants_update_policy'),
  ('20260226_create_condominios_table.sql','table','condominios',null),
  ('20260226_create_condominios_table.sql','function','update_condominios_updated_at',null),
  ('20260226_create_condominios_table.sql','index','idx_condominios_tenant_id',null),
  ('20260304_add_fotos_to_condominios.sql','column','condominios','fotos'),
  ('20260304_create_imoveis_locais.sql','table','imoveis_locais',null),
  ('20260304_create_imoveis_locais.sql','index','idx_imoveis_locais_tenant',null),
  ('20260304_create_imoveis_locais.sql','index','idx_imoveis_locais_codigo',null),
  ('20260313_add_metragens_condominios.sql','index','idx_condominios_metragens',null),
  ('20260313_add_metragens_condominios.sql','index','idx_imoveis_locais_condominio',null),
  ('20260313_add_metragens_condominios.sql','index','idx_imoveis_locais_metragem',null),
  ('20260313_add_status_aprovacao.sql','index','idx_imoveis_locais_status_aprovacao',null),
  ('20260313_add_status_aprovacao.sql','index','idx_condominios_status_aprovacao',null),
  ('20260313_add_status_aprovacao.sql','column','imoveis_locais','status_aprovacao'),
  ('20260327_add_tenant_admin_update_delete_policy_to_memberships.sql','policy','tenant_memberships','memberships_update_tenant_admin'),
  ('20260327_add_tenant_admin_update_delete_policy_to_memberships.sql','policy','tenant_memberships','memberships_delete_tenant_admin'),
  ('20260330_create_admin_test_results.sql','table','admin_test_results',null),
  ('20260330_create_admin_test_results.sql','function','update_admin_test_results_updated_at',null),
  ('20260330_create_admin_test_results.sql','index','idx_admin_test_results_user_id',null),
  ('20260401_add_property_exclusivity_and_bolsao_config.sql','table','tenant_bolsao_config',null),
  ('20260401_add_property_exclusivity_and_bolsao_config.sql','index','idx_imoveis_locais_tenant_exclusivo',null),
  ('20260401_add_property_exclusivity_and_bolsao_config.sql','index','idx_imoveis_corretores_tenant_exclusivo',null),
  ('20260401_create_tenant_lead_limit_config.sql','table','tenant_lead_limit_config',null),
  ('20260401_create_tenant_lead_limit_config.sql','function','update_tenant_lead_limit_config_updated_at',null),
  ('20260401_create_tenant_lead_limit_config.sql','index','idx_tenant_lead_limit_config_tenant',null),
  ('20260402_add_archive_fields_to_kenlo_leads.sql','index','idx_kenlo_leads_archived_at',null),
  ('20260402_add_archive_fields_to_kenlo_leads.sql','index','idx_kenlo_leads_tenant_archived',null),
  ('20260402_add_archive_fields_to_kenlo_leads.sql','column','kenlo_leads','archived_at'),
  ('20260415_create_imoveis_geolocalizacao.sql','table','imoveis_geolocalizacao',null),
  ('20260415_create_imoveis_geolocalizacao.sql','function','update_imoveis_geo_updated_at',null),
  ('20260415_create_imoveis_geolocalizacao.sql','index','idx_imoveis_geo_tenant_status',null),
  ('20260427_mirror_leads_and_kenlo_into_bolsao.sql','function','tg_mirror_leads_to_bolsao',null),
  ('20260427_mirror_leads_and_kenlo_into_bolsao.sql','function','tg_mirror_kenlo_leads_to_bolsao',null),
  ('20260427_mirror_leads_and_kenlo_into_bolsao.sql','function','tg_leads_status_to_bolsao',null),
  ('20260428_add_fonte_column.sql','index','idx_recruitment_candidates_fonte',null),
  ('20260428_add_fonte_column.sql','column','recruitment_candidates','fonte'),
  ('20260428_add_participa_bolsao_flag_to_leads.sql','function','tg_mirror_leads_to_bolsao',null),
  ('20260428_add_participa_bolsao_flag_to_leads.sql','column','leads','participa_bolsao'),
  ('20260428_create_recruitment_candidates.sql','table','recruitment_candidates',null),
  ('20260428_create_recruitment_candidates.sql','table','recruitment_stages',null),
  ('20260428_create_recruitment_candidates.sql','function','update_updated_at_column',null),
  ('20260428_enable_pg_cron_and_bolsao_master_switch.sql','column','tenant_bolsao_config','bolsao_enabled'),
  ('20260428_fix_bolsao_triggers_and_add_server_expiration.sql','function','tg_mirror_leads_to_bolsao',null),
  ('20260428_fix_bolsao_triggers_and_add_server_expiration.sql','function','tg_leads_status_to_bolsao',null),
  ('20260428_fix_bolsao_triggers_and_add_server_expiration.sql','function','expire_bolsao_leads',null),
  ('20260428_roleta_auto_assign_on_leads_insert.sql','function','pick_roleta_broker',null),
  ('20260428_roleta_auto_assign_on_leads_insert.sql','function','tg_assign_roleta_to_leads',null),
  ('20260428_roleta_auto_assign_on_leads_insert.sql','column','roleta_participantes','last_assigned_at'),
  ('20260428_roleta_redistribute_on_expiration.sql','function','tg_update_leads_assigned_at',null),
  ('20260428_roleta_redistribute_on_expiration.sql','function','pick_roleta_broker_excluding',null),
  ('20260428_roleta_redistribute_on_expiration.sql','function','expire_bolsao_leads',null),
  ('20260429_create_corretor_metrics.sql','table','corretor_metrics',null),
  ('20260429_create_corretor_metrics.sql','function','update_corretor_metrics_updated_at',null),
  ('20260429_create_corretor_metrics.sql','function','calcular_corretor_metrics',null),
  ('20260429_create_count_leads_mensal.sql','function','count_leads_mensal',null),
  ('20260429_create_sales_transactions.sql','table','sales_transactions',null),
  ('20260429_create_sales_transactions.sql','function','update_sales_transactions_updated_at',null),
  ('20260429_create_sales_transactions.sql','index','idx_sales_transactions_tenant_id',null),
  ('20260429_create_team_metrics.sql','table','team_metrics',null),
  ('20260429_create_team_metrics.sql','function','update_team_metrics_updated_at',null),
  ('20260429_create_team_metrics.sql','function','calcular_team_metrics',null),
  ('20260429_fix_team_metrics_rls.sql','policy','team_metrics','Users can view their tenant''s team metrics'),
  ('20260429_fix_team_metrics_rls.sql','policy','team_metrics','Users can insert their tenant''s team metrics'),
  ('20260429_fix_team_metrics_rls.sql','policy','team_metrics','Users can update their tenant''s team metrics'),
  ('20260429_fix_teams_rls.sql','policy','teams','Users can view their tenant''s teams'),
  ('20260429_fix_teams_rls.sql','policy','teams','Users can insert their tenant''s teams'),
  ('20260429_fix_teams_rls.sql','policy','teams','Users can update their tenant''s teams'),
  ('20260430_add_creci_column.sql','column','recruitment_candidates','creci'),
  ('20260505_create_excel_imports_if_missing.sql','table','excel_imports',null),
  ('20260505_create_excel_imports_if_missing.sql','index','excel_imports_tenant_year_idx',null),
  ('20260505_create_excel_imports_if_missing.sql','index','excel_imports_corretor_idx',null),
  ('20260508_add_first_response_at_to_kenlo_leads.sql','column','kenlo_leads','first_response_at'),
  ('20260508_add_first_response_at_to_leads.sql','column','leads','first_response_at'),
  ('20260513_create_commercial_sales_sync.sql','table','commercial_sales_import_batches',null),
  ('20260513_create_commercial_sales_sync.sql','table','commercial_sales',null),
  ('20260513_create_commercial_sales_sync.sql','view','commercial_sales_monthly_summary',null),
  ('20260515_add_condominio_lazer_fields.sql','column','condominios','infra_mirante'),
  ('20260517_allow_owner_commercial_sales.sql','policy','commercial_sales','Members can view commercial sales'),
  ('20260517_allow_owner_commercial_sales.sql','policy','commercial_sales','Managers can write commercial sales'),
  ('20260517_allow_owner_commercial_sales.sql','policy','commercial_sales_import_batches','Members can view commercial sales import batches'),
  ('20260517_create_webhook_outbox.sql','table','webhook_subscriptions',null),
  ('20260517_create_webhook_outbox.sql','table','webhook_events',null),
  ('20260517_create_webhook_outbox.sql','function','enqueue_lead_created_webhook',null),
  ('20260518_link_tarefas_semanais_agenda.sql','index','idx_tarefas_semanais_agenda_evento_id',null),
  ('20260518_link_tarefas_semanais_agenda.sql','column','tarefas_semanais','agenda_evento_id'),
  ('20260518_sync_tarefas_from_agenda_eventos.sql','function','sync_tarefa_semanal_from_agenda_evento',null),
  ('20260519_add_transaction_form_to_proposals.sql','index','idx_proposals_transaction_form_gin',null),
  ('20260519_add_transaction_form_to_proposals.sql','column','proposals','transaction_form'),
  ('20260519_create_proposals.sql','table','proposals',null),
  ('20260519_create_proposals.sql','table','proposal_parties',null),
  ('20260519_create_proposals.sql','table','proposal_history',null),
  ('20260520_create_lancamentos.sql','table','lancamentos',null),
  ('20260520_create_lancamentos.sql','index','idx_lancamentos_tenant',null),
  ('20260520_create_lancamentos.sql','index','idx_lancamentos_criado_por',null),
  ('20260520_create_lancamentos_bucket.sql','policy','storage','Authenticated users can upload lancamentos arquivos'),
  ('20260520_create_lancamentos_bucket.sql','policy','storage','Public can view lancamentos arquivos'),
  ('20260520_create_lancamentos_bucket.sql','policy','storage','Authenticated users can update lancamentos arquivos'),
  ('20260521_create_agent_conversations.sql','table','agent_conversations',null),
  ('20260521_create_agent_conversations.sql','table','agent_messages',null),
  ('20260521_create_agent_conversations.sql','function','sync_agent_conversation_on_message',null),
  ('20260521_create_condominios_fotos_bucket.sql','policy','storage','Authenticated users can upload condominios fotos'),
  ('20260521_create_condominios_fotos_bucket.sql','policy','storage','Public can view condominios fotos'),
  ('20260521_create_condominios_fotos_bucket.sql','policy','storage','Authenticated users can update condominios fotos'),
  ('20260522_agent_conversations_owner_visibility.sql','policy','agent_conversations','agent_conversations_select_own_or_manager'),
  ('20260522_agent_conversations_owner_visibility.sql','policy','agent_messages','agent_messages_select_own_or_manager'),
  ('20260522_agent_conversations_owner_visibility.sql','policy','agent_conversations','agent_conversations_update_own'),
  ('20260522_auto_create_corretor_on_membership.sql','function','ensure_corretor_row_on_membership',null),
  ('20260522_fix_agent_conversations_rls_owner.sql','policy','agent_conversations','agent_conversations_insert_own'),
  ('20260522_fix_agent_conversations_rls_owner.sql','policy','agent_messages','agent_messages_insert_own'),
  ('20260527_create_imoveis_fotos_bucket.sql','policy','storage','Authenticated users can upload imoveis fotos'),
  ('20260527_create_imoveis_fotos_bucket.sql','policy','storage','Public can view imoveis fotos'),
  ('20260527_create_imoveis_fotos_bucket.sql','policy','storage','Authenticated users can update imoveis fotos'),
  ('20260528_create_whatsapp_chat.sql','table','whatsapp_config',null),
  ('20260528_create_whatsapp_chat.sql','table','whatsapp_conversations',null),
  ('20260528_create_whatsapp_chat.sql','table','whatsapp_messages',null),
  ('20260528_create_whatsapp_media_bucket.sql','policy','storage','Authenticated users can upload whatsapp media'),
  ('20260528_create_whatsapp_media_bucket.sql','policy','storage','Public can view whatsapp media'),
  ('20260528_create_whatsapp_media_bucket.sql','policy','storage','Authenticated users can update whatsapp media'),
  ('20260529_add_comodidades_troca_to_imoveis_locais.sql','column','imoveis_locais','area_comum'),
  ('20260529_fix_imoveis_corretores_rls.sql','policy','imoveis_corretores','Membros podem ver mapeamentos do tenant'),
  ('20260529_fix_imoveis_corretores_rls.sql','policy','imoveis_corretores','Membros podem criar mapeamentos'),
  ('20260529_fix_imoveis_corretores_rls.sql','policy','imoveis_corretores','Membros podem atualizar mapeamentos do tenant'),
  ('20260601_create_tenant_lead_source_costs.sql','table','tenant_lead_source_costs',null),
  ('20260601_create_tenant_lead_source_costs.sql','function','update_tenant_lead_source_costs_updated_at',null),
  ('20260601_create_tenant_lead_source_costs.sql','index','idx_tenant_lead_source_costs_tenant',null),
  ('20260601_proposals_unique_lead.sql','index','uq_proposals_tenant_lead',null),
  ('20260602_add_endereco_plantao_lancamentos.sql','column','lancamentos','endereco_plantao'),
  ('20260602_mirror_leads_into_proposals.sql','function','proposals_stage_from_lead',null),
  ('20260602_mirror_leads_into_proposals.sql','function','tg_mirror_lead_to_proposal',null),
  ('20260602_proposals_restrict_corretor_read.sql','function','proposals_is_tenant_manager',null),
  ('20260602_proposals_restrict_corretor_read.sql','function','proposals_lead_assigned_to_me',null),
  ('20260602_proposals_restrict_corretor_read.sql','policy','proposals','Tenant members can view proposals'),
  ('20260608_create_watermark_pipeline.sql','table','property_photos',null),
  ('20260608_create_watermark_pipeline.sql','table','watermark_jobs',null),
  ('20260608_create_watermark_pipeline.sql','function','claim_watermark_jobs',null),
  ('20260610_watermark_fixes.sql','table','watermark_reprocess',null),
  ('20260610_watermark_fixes.sql','function','set_photo_derivative',null),
  ('20260610_watermark_fixes.sql','index','uq_property_photos_dedup',null),
  ('20260612_add_watermark_position.sql','column','tenants','watermark_position'),
  ('20260612_create_tenant_lead_source_channels.sql','table','tenant_lead_source_channels',null),
  ('20260612_create_tenant_lead_source_channels.sql','function','update_tenant_lead_source_channels_updated_at',null),
  ('20260612_create_tenant_lead_source_channels.sql','index','idx_tenant_lead_source_channels_tenant',null),
  ('20260615_create_lead_recommendations.sql','table','lead_recommendations',null),
  ('20260615_create_lead_recommendations.sql','index','idx_lead_recommendations_tenant',null),
  ('20260615_create_lead_recommendations.sql','index','idx_lead_recommendations_lead',null),
  ('20260615_create_metas.sql','table','goals',null),
  ('20260615_create_metas.sql','table','goal_history',null),
  ('20260615_create_metas.sql','function','update_goals_updated_at',null),
  ('20260615_create_tenant_recommendation_config.sql','table','tenant_recommendation_config',null),
  ('20260615_create_tenant_recommendation_config.sql','function','update_tenant_recommendation_config_updated_at',null),
  ('20260615_create_tenant_recommendation_config.sql','index','idx_tenant_recommendation_config_tenant',null),
  ('20260616_add_tenant_smtp_config.sql','table','tenant_email_secrets',null),
  ('20260616_add_tenant_smtp_config.sql','function','update_tenant_email_secrets_updated_at',null),
  ('20260616_add_tenant_smtp_config.sql','column','tenant_recommendation_config','smtp_host'),
  ('20260616_create_assign_broker_to_leads_rpc.sql','function','assign_broker_to_leads',null),
  ('20260616_metas_autosync_featured.sql','index','uq_goals_one_featured_per_tenant',null),
  ('20260616_metas_autosync_featured.sql','column','goals','source'),
  ('20260616_metas_autosync_featured.sql','column','goals','scope'),
  ('20260617_add_recommendation_channels.sql','table','lead_recommendation_preferences',null),
  ('20260617_add_recommendation_channels.sql','index','idx_lead_recommendations_idempotency',null),
  ('20260617_add_recommendation_channels.sql','index','idx_lead_recommendations_channel',null),
  ('20260617_fix_agent_conversations_insert_tenant_gate.sql','policy','agent_conversations','agent_conversations_insert_own'),
  ('20260617_fix_recruitment_rls_and_functions.sql','function','search_candidates',null),
  ('20260617_fix_recruitment_rls_and_functions.sql','function','get_recruitment_metrics',null),
  ('20260617_fix_recruitment_rls_and_functions.sql','policy','recruitment_candidates','recruitment_candidates_tenant_isolation'),
  ('20260617_fix_team_metrics_rls_isolation.sql','policy','team_metrics','team_metrics_select'),
  ('20260617_fix_team_metrics_rls_isolation.sql','policy','team_metrics','team_metrics_insert'),
  ('20260617_fix_team_metrics_rls_isolation.sql','policy','team_metrics','team_metrics_update'),
  ('20260617_fix_tenant_source_images_rls.sql','policy','tenant_source_images','tenant_source_images_tenant_isolation'),
  ('20260617_reenable_rls_excel_imports.sql','policy','excel_imports','excel_imports_tenant_isolation'),
  ('20260618_create_generic_imports.sql','table','generic_imports',null),
  ('20260618_create_generic_imports.sql','index','generic_imports_tenant_idx',null),
  ('20260618_create_generic_imports.sql','index','generic_imports_metadata_gin',null),
  ('20260618_create_recommendation_schedules.sql','table','recommendation_schedules',null),
  ('20260618_create_recommendation_schedules.sql','function','update_recommendation_schedules_updated_at',null),
  ('20260618_create_recommendation_schedules.sql','index','idx_rec_schedules_due',null),
  ('20260618_fix_guc_rls_and_count_leads.sql','policy','public','%I'),
  ('20260618_update_recommendation_cadence.sql','column','tenant_recommendation_config','recommendation_interval_days'),
  ('20260618_update_recommendation_cadence.sql','column','recommendation_schedules','interval_days'),
  ('20260619_add_recovery_agent_config.sql','column','tenant_recommendation_config','recovery_agent_enabled'),
  ('20260619_create_recovery_queue.sql','table','recovery_queue',null),
  ('20260619_create_recovery_queue.sql','index','idx_recovery_queue_pending',null),
  ('20260619_create_recovery_queue.sql','index','idx_recovery_queue_tenant',null),
  ('20260619_enqueue_recovery_on_archive.sql','function','tg_enqueue_recovery_on_archive',null),
  ('20260620_create_agent_action_queue.sql','table','agent_action_runs',null),
  ('20260620_create_agent_action_queue.sql','table','agent_action_queue',null),
  ('20260620_create_agent_action_queue.sql','index','idx_agent_action_runs_tenant',null),
  ('20260620_create_dashboard_kpis.sql','table','dashboard_kpis',null),
  ('20260620_create_dashboard_kpis.sql','table','kpi_import_batches',null),
  ('20260620_create_dashboard_kpis.sql','table','kpi_targets',null),
  ('20260624_create_platform_owners.sql','table','platform_owners',null),
  ('20260624_create_platform_owners.sql','function','platform_owners_lowercase_email',null),
  ('20260624_create_platform_owners.sql','function','is_platform_owner',null),
  ('20260624_owner_policies_lote1_alta.sql','function','proposals_can_access_tenant',null),
  ('20260624_owner_policies_lote1_alta.sql','function','proposals_is_tenant_manager',null),
  ('20260624_owner_policies_lote1_alta.sql','function','search_candidates',null),
  ('20260624_owner_policies_lote2_media.sql','policy','tenants','tenants_select_policy'),
  ('20260624_owner_policies_lote2_media.sql','policy','tenants','tenants_insert_policy'),
  ('20260624_owner_policies_lote2_media.sql','policy','tenants','tenants_update_policy'),
  ('20260624_owner_policies_lote2b_consolida.sql','policy','imoveis_corretores','imoveis_corretores_tenant'),
  ('20260624_owner_policies_lote2b_consolida.sql','policy','imoveis_locais','imoveis_locais_tenant'),
  ('20260624_owner_policies_lote2b_consolida.sql','policy','tenants','tenants_select'),
  ('20260625_create_agent_public_source_config.sql','table','agent_public_source_config',null),
  ('20260625_create_agent_public_source_config.sql','function','update_agent_public_source_config_updated_at',null),
  ('20260625_create_agent_public_source_config.sql','policy','agent_public_source_config','agent_public_source_config_select'),
  ('20260625_create_audiences.sql','table','audiences',null),
  ('20260625_create_audiences.sql','function','update_audiences_updated_at',null),
  ('20260625_create_audiences.sql','index','idx_audiences_tenant',null),
  ('20260625_create_communication_templates.sql','table','communication_templates',null),
  ('20260625_create_communication_templates.sql','function','update_communication_templates_updated_at',null),
  ('20260625_create_communication_templates.sql','index','idx_comm_templates_tenant',null),
  ('20260625_encrypt_kenlo_integrations.sql','index','idx_kenlo_integrations_status',null),
  ('20260625_encrypt_kenlo_integrations.sql','column','kenlo_integrations','kenlo_password_encrypted'),
  ('20260625_enqueue_lead_created_kenlo_leads.sql','function','enqueue_lead_created_webhook',null),
  ('20260625_extend_agent_action_queue_backoff.sql','column','agent_action_queue','next_attempt_at'),
  ('20260625_extend_agent_action_runs_dualrun.sql','column','agent_action_runs','public_source_diagnostic'),
  ('20260625_index_agent_action_queue_run_status.sql','index','idx_agent_action_queue_run_status',null),
  ('20260626_add_recurrence_to_campaigns.sql','column','communication_campaigns','recurrence'),
  ('20260626_add_scheduling_to_campaigns.sql','index','idx_comm_campaigns_due',null),
  ('20260626_add_scheduling_to_campaigns.sql','column','communication_campaigns','scheduled_at'),
  ('20260626_add_sync_state_to_kenlo_integrations.sql','column','kenlo_integrations','last_full_sync_at'),
  ('20260626_add_template_name_to_runs_queue.sql','column','agent_action_runs','template_name'),
  ('20260626_add_template_name_to_runs_queue.sql','column','agent_action_queue','template_name'),
  ('20260626_add_variable_mapping_to_runs.sql','column','agent_action_runs','variable_mapping'),
  ('20260626_create_communication_campaigns.sql','table','communication_campaigns',null),
  ('20260626_create_communication_campaigns.sql','function','update_communication_campaigns_updated_at',null),
  ('20260626_create_communication_campaigns.sql','index','idx_comm_campaigns_tenant',null),
  ('20260626_create_tenant_santa_angela_config.sql','table','tenant_santa_angela_config',null),
  ('20260626_create_tenant_santa_angela_config.sql','index','idx_tsa_config_status',null),
  ('20260626_create_tenant_zap_config.sql','table','tenant_zap_config',null),
  ('20260626_create_tenant_zap_config.sql','index','idx_zap_config_secret_lookup',null),
  ('20260626_create_tenant_zap_config.sql','index','idx_zap_config_status',null),
  ('20260627_add_kenlo_fingerprint_to_kenlo_leads.sql','column','kenlo_leads','kenlo_fingerprint'),
  ('20260701_add_webhook_response_columns.sql','column','webhook_events','response_status'),
  ('20260701_add_webhook_response_columns.sql','column','webhook_events','response_body'),
  ('20260701_normalize_lead_created_payload.sql','function','enqueue_lead_created_webhook',null),
  ('20260702_ensure_whatsapp_conversation_on_lead_created.sql','function','ensure_whatsapp_conversation_for_lead',null),
  ('20260702_ensure_whatsapp_conversation_on_lead_created.sql','column','whatsapp_conversations','lead_source_table'),
  ('20260703_add_observacao_to_lead_created_payload.sql','function','enqueue_lead_created_webhook',null),
  ('20260703_add_soft_delete_to_tenants.sql','view','abaixo',null),
  ('20260703_add_soft_delete_to_tenants.sql','view','my_memberships_with_tenant',null),
  ('20260703_add_soft_delete_to_tenants.sql','column','tenants','deleted_at'),
  ('20260706_add_source_crm_and_backfill_flag_to_kenlo_leads.sql','column','kenlo_leads','source_crm'),
  ('20260706_create_tenant_contact2sale_config.sql','table','tenant_contact2sale_config',null),
  ('20260706_create_tenant_contact2sale_config.sql','index','idx_tc2s_config_status',null),
  ('20260706_enqueue_recovery_on_archive_kenlo_leads.sql','function','enqueue_recovery_from_kenlo_lead',null),
  ('20260706_enqueue_recovery_on_archive_kenlo_leads.sql','function','tg_enqueue_recovery_on_archive_kenlo',null),
  ('20260706_enqueue_recovery_on_archive_kenlo_leads.sql','function','tg_enqueue_recovery_on_insert_kenlo',null),
  ('20260706_provider_exclusivity.sql','function','deactivate_other_crm_provider',null),
  ('20260706_webhook_gate_backfill_freshness.sql','column','kenlo_leads','is_backfill'),
  ('20260711_create_job_heartbeats.sql','table','job_heartbeats',null),
  ('20260713_index_kenlo_attended_by_name_trgm.sql','index','idx_kenlo_leads_attended_by_name_trgm',null),
  ('20260714_add_condominio_gas_encanado.sql','column','condominios','infra_gas_encanado'),
  ('20260715_c2s_revisit_days.sql','column','tenant_contact2sale_config','revisit_days'),
  ('20260717_add_lancamentos_filter_fields.sql','column','lancamentos','tipo_dorms'),
  ('20260717_create_portal_lancamentos_view.sql','view','portal_lancamentos',null),
  ('20260717_create_portal_lancamentos_view.sql','policy','lancamentos','portal_anon_select_lancamentos'),
  ('20260717_create_portal_public_views.sql','view','portal_condominios',null),
  ('20260717_create_portal_public_views.sql','view','portal_imoveis',null),
  ('20260717_create_portal_public_views.sql','policy','condominios','portal_anon_select_condominios'),
  ('20260717_enrich_lancamentos_for_portal.sql','column','lancamentos','cidade'),
  ('20260717_portal_revalidate_trigger.sql','table','portal_config',null),
  ('20260717_portal_revalidate_trigger.sql','function','portal_revalidate',null),
  ('20260721_c2s_revisit_interval.sql','column','tenant_contact2sale_config','last_revisit_at'),
  ('20260722_add_creci_to_tenant_memberships.sql','column','tenant_memberships','creci'),
  ('20260724_create_agent_telemetry_events.sql','table','agent_telemetry_events',null),
  ('20260724_create_agent_telemetry_events.sql','index','idx_agent_telemetry_tenant_time',null),
  ('20260724_create_agent_telemetry_events.sql','index','idx_agent_telemetry_agent_time',null),
  ('20260725_agent_telemetry_aggregations.sql','function','agent_telemetry_summary',null),
  ('20260725_agent_telemetry_aggregations.sql','function','agent_telemetry_timeseries',null),
  ('20260725_agent_telemetry_aggregations.sql','function','agent_telemetry_errors',null),
  ('20260727_create_enps_tables.sql','table','surveys',null),
  ('20260727_create_enps_tables.sql','table','survey_cycles',null),
  ('20260727_create_enps_tables.sql','table','survey_dispatches',null),
  ('20260727_enps_add_indexes.sql','index','survey_responses_cycle',null),
  ('20260727_enps_add_indexes.sql','index','survey_dispatches_by_respondent',null),
  ('20260728_index_tenant_created_kenlo_leads_and_leads.sql','index','idx_kenlo_leads_tenant_created',null),
  ('20260728_index_tenant_created_kenlo_leads_and_leads.sql','index','idx_leads_tenant_created',null),
  ('20260729_create_agent_response_evaluations.sql','table','agent_response_evaluations',null),
  ('20260729_create_agent_response_evaluations.sql','index','idx_agent_response_eval_tenant_time',null),
  ('20260729_create_agent_response_evaluations.sql','policy','agent_response_evaluations','agent_response_eval_select'),
  ('20260729_create_exchange_rates.sql','table','exchange_rates',null),
  ('20260729_create_exchange_rates.sql','index','idx_exchange_rates_pair_eff',null),
  ('20260729_create_exchange_rates.sql','policy','exchange_rates','exchange_rates_select'),
  ('20260729_create_tenant_anthropic_config.sql','table','tenant_anthropic_config',null),
  ('20260729_create_tenant_anthropic_config.sql','index','idx_tenant_anthropic_config_status',null),
  ('20260730_anthropic_fase2_threshold_alert.sql','column','tenant_anthropic_config','alert_threshold_bps'),
  ('20260730_anthropic_fase3_mode.sql','column','tenant_anthropic_config','mode'),
  ('20260731_add_site_url_lancamentos.sql','column','lancamentos','site_url'),
  ('20260805_add_last_error_to_webhook_events.sql','column','webhook_events','last_error'),
  ('20260805_enqueue_lead_revived_webhook.sql','function','enqueue_lead_created_webhook',null),
  ('20260806_create_meta_leadgen.sql','table','tenant_meta_leadgen_config',null),
  ('20260806_create_meta_leadgen.sql','table','meta_leadgen_events',null),
  ('20260806_create_meta_leadgen.sql','index','idx_meta_leadgen_config_status',null),
  ('20260810_add_captador_to_imoveis_condominios.sql','function','tg_guard_captador',null),
  ('20260810_add_captador_to_imoveis_condominios.sql','index','idx_imoveis_locais_captador',null),
  ('20260810_add_captador_to_imoveis_condominios.sql','index','idx_condominios_captador',null),
  ('20260810_add_publicacao_to_imoveis_locais.sql','view','portal_imoveis',null),
  ('20260810_add_publicacao_to_imoveis_locais.sql','column','imoveis_locais','publicar_site'),
  ('20260810_add_publicacao_to_imoveis_locais.sql','policy','imoveis_locais','portal_anon_select_imoveis_locais'),
  ('20260810_kenlo_leads_attended_by_idx.sql','index','idx_kenlo_leads_tenant_attended_by_name',null),
  ('20260810_kenlo_leads_attended_by_idx.sql','index','idx_kenlo_leads_tenant_attended_by_id',null),
  ('20260810_kenlo_leads_count_by_broker.sql','function','kenlo_leads_count_by_broker',null),
  ('20260812_enps_identificado_comentario_anonimo.sql','table','survey_comments',null),
  ('20260812_enps_identificado_comentario_anonimo.sql','index','survey_comments_cycle',null),
  ('20260812_sync_bolsao_codigo.sql','function','tg_leads_codigo_to_bolsao',null),
  ('20260812_sync_bolsao_codigo.sql','function','tg_kenlo_leads_codigo_to_bolsao',null),
  ('20260813_add_obs_interna_to_imoveis_locais.sql','column','imoveis_locais','obs_interna'),
  ('20260815_add_lead_classification.sql','function','normalizar_texto',null),
  ('20260815_add_lead_classification.sql','function','classificar_lead_transacao',null),
  ('20260815_add_lead_classification.sql','function','classificar_lead_estagio',null),
  ('20260815_lead_classification_triggers.sql','function','tg_leads_classificar',null),
  ('20260815_lead_classification_triggers.sql','function','tg_kenlo_leads_classificar',null),
  ('20260815_lead_classification_triggers.sql','function','tg_classification_source_guard',null),
  ('20260816_whatsapp_conversation_visibility.sql','function','can_read_whatsapp_conversation',null),
  ('20260816_whatsapp_conversation_visibility.sql','index','idx_whatsapp_conversations_tenant_assigned',null),
  ('20260816_whatsapp_conversation_visibility.sql','policy','whatsapp_conversations','whatsapp_conversations_select_tenant'),
  ('20260817_add_my_maps_mid_to_tenant_xml_config.sql','column','tenant_xml_config','my_maps_mid'),
  ('20260817_imoveis_locais_log.sql','table','imoveis_locais_log',null),
  ('20260817_imoveis_locais_log.sql','function','imoveis_locais_log_resumo',null),
  ('20260817_imoveis_locais_log.sql','function','log_imoveis_locais_alteracoes',null),
  ('20260817_imoveis_locais_touch_updated_at.sql','function','touch_imoveis_locais_updated_at',null),
  ('20260818_agent_messages_relatorio_subject.sql','policy','agent_messages','agent_messages_select_own_or_manager'),
  ('20260818_lead_classification_multi.sql','function','tg_leads_classificar',null),
  ('20260818_lead_classification_multi.sql','function','tg_kenlo_leads_classificar',null),
  ('20260819_imoveis_chaves.sql','function','imoveis_locais_carimbar_chave',null),
  ('20260819_imoveis_chaves.sql','column','imoveis_locais','chave_status'),
  ('20260819_lead_preferences.sql','column','leads','preferences'),
  ('20260819_lead_preferences.sql','column','kenlo_leads','preferences'),
  ('20260820_proposals_forecast_fields.sql','column','proposals','forecast_empreendimento'),
  ('20260823_whatsapp_conversation_category.sql','column','whatsapp_conversations','category'),
  ('20260824_bolsao_enable_rls.sql','policy','bolsao','bolsao_tenant_select'),
  ('20260824_bolsao_enable_rls.sql','policy','bolsao','bolsao_tenant_insert'),
  ('20260824_bolsao_enable_rls.sql','policy','bolsao','bolsao_tenant_update'),
  ('20260824_fix_proposals_write_bola.sql','policy','proposals','Tenant members can write proposals'),
  ('20260824_fix_proposals_write_bola.sql','policy','proposals','proposals_insert_owner_or_manager'),
  ('20260824_fix_proposals_write_bola.sql','policy','proposals','proposals_update_owner_or_manager'),
  ('20260824_lead_cpf_documentos.sql','column','leads','cpf'),
  ('20260824_lead_cpf_documentos.sql','column','kenlo_leads','cpf'),
  ('20260824_lead_cpf_documentos.sql','policy','storage','Authenticated users can upload lead documentos'),
  ('20260825_proposals_forecast_oculto.sql','column','proposals','forecast_oculto'),
  ('20260825_proposals_forecast_oculto.sql','policy','proposals','proposals_update_owner_or_manager'),
  ('20260825_teams_multi_gestor.sql','column','teams','leader_user_ids'),
  ('20260826_whatsapp_gestor_atuacao_visibility.sql','function','classificacoes_da_atuacao',null),
  ('20260826_whatsapp_gestor_atuacao_visibility.sql','function','can_read_whatsapp_conversation',null),
  ('20260826_whatsapp_gestor_atuacao_visibility.sql','policy','whatsapp_conversations','whatsapp_conversations_select_tenant'),
  ('20260827_ga_integrations.sql','table','ga_integrations',null),
  ('20260827_ga_integrations.sql','policy','ga_integrations','ga_integrations_select'),
  ('20260827_ga_integrations.sql','policy','ga_integrations','ga_integrations_write'),
  ('20260828_notify_gestor_imovel_pendente.sql','function','notify_gestor_imovel_pendente',null),
  ('20260828_proposals_signed_at_commission.sql','function','tg_proposals_set_signed_at',null),
  ('20260828_proposals_signed_at_commission.sql','column','proposals','signed_at'),
  ('20260830_whatsapp_gestor_equipe_visibility.sql','function','can_read_whatsapp_conversation',null),
  ('20260831_admin_update_member_credentials.sql','function','caller_can_manage_user',null),
  ('20260831_admin_update_member_credentials.sql','function','admin_update_user_email',null),
  ('20260831_admin_update_member_credentials.sql','function','admin_update_user_password',null),
  ('20260902_add_hide_complement_to_zap_config.sql','column','tenant_zap_config','hide_complement'),
  ('20260902_captador2_e_captador_edita.sql','function','tg_guard_captador',null),
  ('20260902_captador2_e_captador_edita.sql','column','imoveis_locais','captador_2_id'),
  ('20260902_captador2_e_captador_edita.sql','column','condominios','captador_2_id'),
  ('20260903_classificacao_lancamento_e_revive.sql','function','eh_codigo_lancamento',null),
  ('20260903_classificacao_lancamento_e_revive.sql','function','classificar_lead_com_lancamento',null),
  ('20260903_classificacao_lancamento_e_revive.sql','function','tg_leads_classificar',null),
  ('20260903_lancamento_anuncios.sql','table','lancamento_anuncios',null),
  ('20260903_lancamento_anuncios.sql','index','lancamento_anuncios_codigo_idx',null),
  ('20260904_proprietario_telefones_extras.sql','index','idx_imoveis_locais_proprietario',null),
  ('20260904_proprietario_telefones_extras.sql','column','imoveis_locais','proprietario_tel_residencial'),
  ('20260905_recrutamento.sql','table','recrut_candidato',null),
  ('20260905_recrutamento.sql','table','recrut_evento',null),
  ('20260905_recrutamento.sql','table','recrut_ativacao_marco',null),
  ('20260905_recrutamento_fila_acao.sql','view','vw_recrut_fila_acao',null),
  ('20260905_recrutamento_fila_acao.sql','index','idx_recrut_marco_pendente',null),
  ('20260906_backfill_recrutamento_legado.sql','function','recrut_norm_phone',null),
  ('20260906_recrut_campos_da_tela.sql','index','idx_recrut_candidato_nome_trgm',null),
  ('20260906_recrut_campos_da_tela.sql','column','recrut_candidato','cargo'),
  ('20260906_recrut_campos_da_tela.sql','column','recrut_candidato','experiencia')
),
checado as (
  select arquivo, tipo, obj, extra,
    case tipo
      when 'table'    then to_regclass('public.' || obj) is not null
      when 'view'     then to_regclass('public.' || obj) is not null
      when 'index'    then to_regclass('public.' || obj) is not null
      when 'type'     then exists (select 1 from pg_type where typname = obj)
      when 'function' then exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
                                    where n.nspname = 'public' and p.proname = obj)
      when 'column'   then exists (select 1 from information_schema.columns
                                    where table_schema = 'public' and table_name = obj and column_name = extra)
      when 'policy'   then exists (select 1 from pg_policies
                                    where schemaname = 'public' and tablename = obj and policyname = extra)
    end as existe
  from alvo
)
select arquivo,
       case when bool_and(existe) then 'APLICADA'
            when bool_or(existe)  then 'PARCIAL'
            else 'FALTANDO' end as status,
       count(*) filter (where not existe) as objetos_ausentes,
       string_agg(tipo || ' ' || obj || coalesce('.' || extra, ''), ', ')
         filter (where not existe) as o_que_falta
  from checado
 group by arquivo
having not bool_and(existe)          -- só o que NÃO está 100% aplicado
 order by arquivo;
